version: '3.8'

services:
  # redis is a redis instance
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
  # db is a postgres instance
  db:
      image: postgres:9.6.12
      environment:
          - POSTGRES_PASSWORD=postgres
      ports:
          - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      # NOTE: db refers to the db service defined below. Docker will automatically resolve this to the container
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db
    # sleep for 5 seconds to give the db time to boot up
    command: >
        sh -c "sleep 5 &&
            java -jar /cs6310/grocery-express-project-0.0.1-SNAPSHOT.jar"

volumes:
  postgres-data: